In [2]:
!pip install tweepy

In [3]:
!pip install python-dotenv


In [4]:
from dotenv import load_dotenv
load_dotenv(dotenv_path="/workspaces/scrape/.gitignore/.env")


True

In [5]:
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

# Test if environment variable is being loaded
print(os.getenv("API_KEY"))  # Should print your API key if loaded correctly


IXcCcUM85jLp6G2g40nMiy6a3


In [6]:
import tweepy
from dotenv import load_dotenv
import os

load_dotenv()
# Replace with your credentials
api_key = os.getenv("API_KEY")
api_secret = os.getenv("API_SECRET")
bearer_token = os.getenv("BEARER_TOKEN")

# Authenticate with the Bearer Token
try:
    client = tweepy.Client(bearer_token=bearer_token)
    print("Authentication successful!")
except Exception as e:
    print(f"Error during authentication: {e}")


Authentication successful!


In [7]:
try:
    # Search for recent tweets containing the term "stocks"
    response = client.search_recent_tweets(query="stocks", max_results=10)
    
    # Display the tweets
    if response.data:
        print("Recent Tweets:")
        for tweet in response.data:
            print(tweet.text)
    else:
        print("No tweets found for the given query.")
except Exception as e:
    print(f"Error fetching tweets: {e}")


Recent Tweets:
@StockMKTNewz Oh, interesting! Could impact stocks
RT @MiatoTechnolog: 🎉 Miato New Year Super Sale!🎉  

Own the reliable HP EliteBook 840 (6th Gen)
✨ 14-inch Display |8GB RAM| 256GB SSD
Now…
Gold has outshined stocks in the 21st century. The DJCI Gold TR index outperformed the S&amp;P 500 TR index not just in 2024 but over the entire period since Dec 31. https://t.co/Z6vXzSTNCL
RT @wallstreetbets: Cardano’s $ADA 11.5% surge is the crypto equivalent of a rollercoaster ride: thrilling, unpredictable, and you might ju…
RT @RepDeluzio: Good morning. It should be illegal for members of Congress to trade stocks. Let’s ban this swampy nonsense.
RT @ericnuttall: It’s refreshing to hear such an energy-literate politician, especially when that person is likely to become Canada’s next…
U.S. stocks are showing weakness, and the dollar’s surge adds to market uncertainty. $SOL/ETH is reversing, and AI projects are seeing a rush of capital. Interesting shifts happening with future list

In [8]:
!pip install nltk

In [9]:
import re #for regular expression to clean text
import nltk #Natural language Toolkit for text processing
from nltk.corpus import stopwords #To remove common, meaningless words
from nltk.tokenize import word_tokenize, sent_tokenize #To break text into tokens (individual words)
from nltk.stem import WordNetLemmatizer

In [10]:
nltk.download('stopwords') #contains words like "and","the","is" etc., which are filtered -> don't carry any significant meaning.
nltk.download('punkt_tab') #a pre-trained tokenizer model for splitting text into sentences and words
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/codespace/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/codespace/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/codespace/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [11]:
#What the package stopwords contains
print(stopwords.words('english'))  # Prints English stopwords


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [12]:
#how punkt Tokenizer works
text = "Hello, world! NLP is amazing."
print(word_tokenize(text))  # Outputs: ['Hello', ',', 'world', '!', 'NLP', 'is', 'amazing', '.']
print(sent_tokenize(text))  # Outputs: ['Hello, world!', 'NLP is amazing.']


['Hello', ',', 'world', '!', 'NLP', 'is', 'amazing', '.']
['Hello, world!', 'NLP is amazing.']


In [13]:
#how WordNetLemmatizer works
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
word = "running"
lemma = lemmatizer.lemmatize(word, pos="v")  # Specify part of speech (v = verb)
print(lemma)  # Output: "run"
print(lemmatizer.lemmatize("better"))  # Output: "better" (default POS is noun)
print(lemmatizer.lemmatize("better", pos="a"))  # Output: "good" (adjective POS)
#pos="n"-Noun "v"=Verb "a"=Adjective "r"-Adverb

run
better
good


In [14]:
#initializing stopwords and lemmatizer
stop_words= set(stopwords.words('english'))
lemmantizer=WordNetLemmatizer()

def preprocess_tweet(tweet):
    #Step 1: remove URLs
    tweet =re.sub(r"http\S+|www.\S+","",tweet)

    #Step 2: remove mentions and hashtags
    tweet =re.sub(r"@\w+|#\w+","",tweet)

    # Step 3: Remove special characters, numbers, and punctuation
    tweet = re.sub(r"[^a-zA-Z\s]", "", tweet)
    
    # Step 4: Convert text to lowercase
    tweet = tweet.lower()
    
    # Step 5: Tokenize the text
    tokens = word_tokenize(tweet)
    
    # Step 6: Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]
    
    # Step 7: Lemmatize the tokens
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Join tokens back into a cleaned sentence
    cleaned_tweet = " ".join(lemmatized_tokens)
    return cleaned_tweet

In [15]:
#1. Fetch Raw Tweets: Assume you have fetched tweets using Tweepy
tweets = [tweet.text for tweet in response.data]

In [16]:
#2. Clean the Tweets: Use the preprocess_tweet function on each tweet
cleaned_tweets =[preprocess_tweet(tweet) for tweet in tweets]

In [17]:
for i, tweet in enumerate(cleaned_tweets, start=1):
    print(f"Cleaned Tweet {i}: {tweet}")

Cleaned Tweet 1: oh interesting could impact stock
Cleaned Tweet 2: rt miato new year super sale reliable hp elitebook th gen inch display gb ram gb ssd
Cleaned Tweet 3: gold outshined stock st century djci gold tr index outperformed sampp tr index entire period since dec
Cleaned Tweet 4: rt cardanos ada surge crypto equivalent rollercoaster ride thrilling unpredictable might ju
Cleaned Tweet 5: rt good morning illegal member congress trade stock let ban swampy nonsense
Cleaned Tweet 6: rt refreshing hear energyliterate politician especially person likely become canada next
Cleaned Tweet 7: u stock showing weakness dollar surge add market uncertainty soleth reversing ai project seeing rush capital interesting shift happening future listing like bio desci
Cleaned Tweet 8: rt miato new year super sale reliable hp elitebook th gen inch display gb ram gb ssd
Cleaned Tweet 9: know everyone want buy dip natural thing certainly stock long period time imo bottom yet buying call prepared lose f

In [18]:
#using vaderSentiment analyser
!pip install vaderSentiment

In [19]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

def get_sentiment(tweet):
    sentiment_score = analyzer.polarity_scores(tweet)
    return sentiment_score['compound'] #Return a score between -1 (negative) and +1 (positive)

sentiments = [get_sentiment(tweet) for tweet in cleaned_tweets]
print(sentiments) #list of sentiment scores for each tweet

[0.4019, 0.5994, 0.0, 0.4767, -0.7906, 0.0, 0.0, 0.5994, 0.5267, 0.8316]


In [20]:
!pip install scikit-learn

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize vectorizer
vectorizer = CountVectorizer(max_features=1000)  # Use the top 1000 words
X = vectorizer.fit_transform(cleaned_tweets).toarray()  # X is a matrix of features
print(X)  # Each row is a tweet, and columns are word frequencies


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize vectorizer
tfidf = TfidfVectorizer(max_features=1000)
X_tfidf = tfidf.fit_transform(cleaned_tweets).toarray()
print(X_tfidf)


[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.2331339  0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.2331339  0.        ]
 [0.19607527 0.         0.         ... 0.         0.         0.19607527]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [23]:
import numpy as np

# Combine features
X_combined = np.hstack((X, np.array(sentiments).reshape(-1, 1)))
print(X_combined)  # Each row includes text features + sentiment score


[[0.     0.     0.     ... 0.     0.     0.4019]
 [0.     0.     0.     ... 1.     0.     0.5994]
 [0.     0.     0.     ... 0.     0.     0.    ]
 ...
 [0.     0.     0.     ... 1.     0.     0.5994]
 [1.     0.     0.     ... 0.     1.     0.5267]
 [0.     0.     0.     ... 0.     0.     0.8316]]
